### PR TITLE
Shortcut to include an access-token in a file

### PR DESCRIPTION
**Pull request by liljenback**
## Description

Access Token can be stored in a file and used when authenticating.

## Related Issue

Maybe:
#63 

## Motivation and Context

I had problems uploading an extension.

## How Has This Been Tested?

I included tests.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by brenthosie** [comment]
@liljenback Thank you for putting in the effort to make a submission to the project. After an internal discussion on your proposed change, we'd prefer to accept the `--access-token` as a raw string value rather than implying it's stored in a file on the user's machine. This would allow the passing of the token securely using CI/CD environment variables as well. If you can make that change, then we can re-review and consider the submission. Thank you!

**Comment by brenthosie** [comment]
@mems `npm install @adobe/auth-token@next` has support for the new `oauth-server-to-server` standard. Does that meet your need?

**Comment by brenthosie** [comment]
Addressed by #66 which allows you to pass in the access token as an environment variable. See `v6.0.0-beta.12`.

**Comment by mems** [comment]
@brenthosie Yes, with the use of `REACTOR_IO_INTEGRATION_ACCESS_TOKEN` env var

**Pull request closed without merging**
